#Dataset Merging

In [ ]:
import pandas as pd

##1. Load all 5 data sets and see which attributes are frequently represented in the data sets

In [ ]:
#Load dataset 1 "Fake and real news dataset" (consisting of 2 separate data sets "True" and "False")
fake_1 = pd.read_csv('Fake1.csv')
true_1 = pd.read_csv('True1.csv')

#Show dataset
fake_1.head()
true_1.head()

#Column names
fake_1.columns
true_1.columns

#Data types of the columns
fake_1.dtypes
true_1.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [ ]:
#Load dataset 2 "Fake News" 
dataset_2 = pd.read_csv('Dataset 2_Fake News.csv')

#Show dataset
dataset_2.head()

#Column names
dataset_2.columns

#Data types of the columns
dataset_2.dtypes

Unnamed: 0     int64
title         object
text          object
label         object
dtype: object

In [ ]:
#Load dataset 3 "Sourced based Fake News Classification"
dataset_3 = pd.read_csv('Dataset 3_Sourced based Fake News Classification.csv')

#Show dataset
dataset_3.head()

#Column names
dataset_3.columns

#Data types of the columns
dataset_3.dtypes

author                      object
published                   object
title                       object
text                        object
language                    object
site_url                    object
main_img_url                object
type                        object
label                       object
title_without_stopwords     object
text_without_stopwords      object
hasImage                   float64
dtype: object

In [ ]:
#Load dataset 4 "Fake news detection"
dataset_4 = pd.read_csv('Dataset 4_Fake news detection.csv')

#Show dataset
dataset_4.head()

#Column names
dataset_4.columns

#Data types of the columns
dataset_4.dtypes

URLs        object
Headline    object
Body        object
Label        int64
dtype: object

In [ ]:
#Error!
#Load dataset 5 "Fake News Dataset"  
#dataset_5 = pd.read_csv('Dataset 5_Fake News Dataset.csv')

#Show dataset
#dataset_5.head()

#Column names
#dataset_5.columns

#Data types of the columns
#dataset_5.dtypes

All datasets contain the attributes title and text. Also, dataset 1 and dataset 3 both have date attributes.

##2. Uniform column names for the same column contents

In [ ]:
# "title" as column name for the articles title
# "text" as column name for the article content
# "date" as column name for the publishing date
# "label" as column name for the label 

#rename columns of dataset 4
dataset_4 = dataset_4.rename(columns={'Headline': 'title', 'Body': 'text', 'Label':'label'})
dataset_4.columns

#rename column of dataset 3
dataset_3 = dataset_3.rename(columns={'published': 'date'})
dataset_3.columns
dataset_3.head()

,author,date,title,text,language,site_url,main_img_url,type,label,title_without_stopwords,text_without_stopwords,hasImage
0,Barracuda Brigade,2016-10-26T21:41:00.000+03:00,muslims busted they stole millions in govt ben...,print they should pay all the back all the mon...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,Real,muslims busted stole millions govt benefits,print pay back money plus interest entire fami...,1.0
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,re why did attorney general loretta lynch plea...,why did attorney general loretta lynch plead t...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,Real,attorney general loretta lynch plead fifth,attorney general loretta lynch plead fifth bar...,1.0
2,Barracuda Brigade,2016-10-31T01:41:49.479+02:00,breaking weiner cooperating with fbi on hillar...,red state \nfox news sunday reported this mor...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,Real,breaking weiner cooperating fbi hillary email ...,red state fox news sunday reported morning ant...,1.0
3,Fed Up,2016-11-01T05:22:00.000+02:00,pin drop speech by father of daughter kidnappe...,email kayla mueller was a prisoner and torture...,english,100percentfedup.com,http://100percentfedup.com/wp-content/uploads/...,bias,Real,pin drop speech father daughter kidnapped kill...,email kayla mueller prisoner tortured isis cha...,1.0
4,Fed Up,2016-11-01T21:56:00.000+02:00,fantastic trumps point plan to reform healthc...,email healthcare reform to make america great ...,english,100percentfedup.com,http://100percentfedup.com/wp-content/uploads/...,bias,Real,fantastic trumps point plan reform healthcare ...,email healthcare reform make america great sin...,1.0

**to do: use same format for date columns in dataset 1 and dataset 3!**

##3. Merge two separate datasets from dataset 1 into one

In [ ]:
fake_1.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true_1.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
# First add a column for the label
fake_1['label'] = 0
fake_1.head()

true_1['label']=1
true_1.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [ ]:
#concat fake_1 and true_1 datasets
dataset_1 = pd.concat([fake_1, true_1], ignore_index=True, sort=False)
len(dataset_1)
dataset_1

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

##4. Uniform labeling of true and fake news in the label column

Fake News = 0; True/Real News = 1

In [ ]:
#dataset 2
dataset_2.label[dataset_2.label == 'FAKE'] = 0
dataset_2.label[dataset_2.label == 'REAL'] = 1
dataset_2

#dataset 3
dataset_3.label[dataset_3.label == 'Fake'] = 0
dataset_3.label[dataset_3.label == 'Real'] = 1
dataset_3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,author,date,title,text,language,site_url,main_img_url,type,label,title_without_stopwords,text_without_stopwords,hasImage
0,Barracuda Brigade,2016-10-26T21:41:00.000+03:00,muslims busted they stole millions in govt ben...,print they should pay all the back all the mon...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,1,muslims busted stole millions govt benefits,print pay back money plus interest entire fami...,1.0
1,reasoning with facts,2016-10-29T08:47:11.259+03:00,re why did attorney general loretta lynch plea...,why did attorney general loretta lynch plead t...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,1,attorney general loretta lynch plead fifth,attorney general loretta lynch plead fifth bar...,1.0
2,Barracuda Brigade,2016-10-31T01:41:49.479+02:00,breaking weiner cooperating with fbi on hillar...,red state \nfox news sunday reported this mor...,english,100percentfedup.com,http://bb4sp.com/wp-content/uploads/2016/10/Fu...,bias,1,breaking weiner cooperating fbi hillary email ...,red state fox news sunday reported morning ant...,1.0
3,Fed Up,2016-11-01T05:22:00.000+02:00,pin drop speech by father of daughter kidnappe...,email kayla mueller was a prisoner and torture...,english,100percentfedup.com,http://100percentfedup.com/wp-content/uploads/...,bias,1,pin drop speech father daughter kidnapped kill...,email kayla mueller prisoner tortured isis cha...,1.0
4,Fed Up,2016-11-01T21:56:00.000+02:00,fantastic trumps point plan to reform healthc...,email healthcare reform to make america great ...,english,100percentfedup.com,http://100percentfedup.com/wp-content/uploads/...,bias,1,fantastic trumps point plan reform healthcare ...,email healthcare reform make america great sin...,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2091,-NO AUTHOR-,2016-10-27T15:36:10.573+03:00,teens walk free after gangrape conviction,NaN,english,wnd.com,http://www.wnd.com/files/2016/10/hillary_haunt...,bias,1,good samaritan wearing indian headdress disarm...,NaN,1.0
2092,-NO AUTHOR-,2016-10-27T15:36:10.671+03:00,school named for munichmassacre mastermind,NaN,english,wnd.com,http://www.wnd.com/files/2016/10/rambo_richard...,bias,1,skype sex scam fortune built shame,NaN,1.0
2093,-NO AUTHOR-,2016-10-27T13:30:00.000+03:00,russia unveils satan missile,NaN,english,wnd.com,http://www.wnd.com/files/2016/10/skype_sex_sca...,bs,0,cannabis aficionados develop thca crystalline ...,NaN,1.0
2094,-NO AUTHOR-,2016-10-27T15:58:41.935+03:00,check out hillarythemed haunted house,NaN,english,wnd.com,http://worldtruth.tv/wp-content/uploads/2016/1...,bs,0,title,NaN,0.0
2095,Eddy Lavine,2016-10-28T01:02:00.000+03:00,cannabis aficionados develop thca crystalline ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##5.Drop unusuable columns and save dataframes under a new name

In [ ]:
#dataset 1: drop subject column and subject+date columns
dataset_1_withdate= dataset_1.drop(['subject'], 1)
dataset_1_withdate.head()

dataset_1_nodate =dataset_1.drop(['subject','date'], 1)
dataset_1_nodate.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0

In [ ]:
#dataset 2: drop column "Unnamed: 0"
dataset_2_new= dataset_2.drop(['Unnamed: 0'], 1)
dataset_2_new.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1

In [ ]:
#dataset 3: drop columns 'author', 'date', 'title', 'text', 'language', 'site_url', 'main_img_url', 'type', 'label', 'title_without_stopwords','text_without_stopwords', 'hasImage'
dataset_3_withdate= dataset_3.drop(['author','language','site_url','main_img_url','type','title_without_stopwords','text_without_stopwords','hasImage'], 1)
dataset_3_nodate= dataset_3.drop(['author','date','language','site_url','main_img_url','type','title_without_stopwords','text_without_stopwords','hasImage'], 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.

,title,text,label
0,muslims busted they stole millions in govt ben...,print they should pay all the back all the mon...,1
1,re why did attorney general loretta lynch plea...,why did attorney general loretta lynch plead t...,1
2,breaking weiner cooperating with fbi on hillar...,red state \nfox news sunday reported this mor...,1
3,pin drop speech by father of daughter kidnappe...,email kayla mueller was a prisoner and torture...,1
4,fantastic trumps point plan to reform healthc...,email healthcare reform to make america great ...,1

In [ ]:
#dataset 4: drop column 'URLs'
dataset_4_new= dataset_4.drop(['URLs'], 1)
dataset_4_new.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

,title,text,label
0,Four ways Bob Corker skewered Donald Trump,Image copyright Getty Images\nOn Sunday mornin...,1
1,Linklater's war veteran comedy speaks to moder...,"LONDON (Reuters) - “Last Flag Flying”, a comed...",1
2,Trump’s Fight With Corker Jeopardizes His Legi...,The feud broke into public view last week when...,1
3,Egypt's Cheiron wins tie-up with Pemex for Mex...,MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...,1
4,Jason Aldean opens 'SNL' with Vegas tribute,"Country singer Jason Aldean, who was performin...",1

##6. Merge datasets

The next step is to merge two data sets at a time. This results in various combinations of data sets.

In [ ]:
#Merge dataset_1_withdate & dataset_3_withdate
dataset_3_4_withdate = pd.concat([dataset_1_withdate, dataset_3_withdate], ignore_index=True, sort=False)
dataset_3_4_withdate.isna().sum()

title     0
text     46
date      0
label     1
dtype: int64

In [ ]:
#Merge dataset_1_nodate & dataset_2_new
dataset_1_2 = pd.concat([dataset_1_nodate, dataset_2_new], ignore_index=True, sort=False)
dataset_1_2

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0
...,...,...,...
51228,State Department says it can't find emails fro...,The State Department told the Republican Natio...,1
51229,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,0
51230,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,0
51231,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",1
51232,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,1

In [ ]:
#Merge dataset_1_nodate & dataset_3_nodate
dataset_1_3 = pd.concat([dataset_1_nodate, dataset_3_nodate], ignore_index=True, sort=False)
dataset_1_3

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0
...,...,...,...
46989,teens walk free after gangrape conviction,NaN,1
46990,school named for munichmassacre mastermind,NaN,1
46991,russia unveils satan missile,NaN,0
46992,check out hillarythemed haunted house,NaN,0
46993,cannabis aficionados develop thca crystalline ...,NaN,NaN

In [ ]:
#Merge dataset_1_nodate & dataset_4_new
dataset_1_4 = pd.concat([dataset_1_nodate, dataset_4_new], ignore_index=True, sort=False)
dataset_1_4

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0
...,...,...,...
48902,Trends to Watch,Trends to Watch\n% of readers think this story...,0
48903,Trump Jr. Is Soon To Give A 30-Minute Speech F...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,0
48904,"Ron Paul on Trump, Anarchism & the AltRight",NaN,0
48905,China to accept overseas trial data in bid to ...,SHANGHAI (Reuters) - China said it plans to ac...,1
48906,Vice President Mike Pence Leaves NFL Game Beca...,Vice President Mike Pence Leaves NFL Game Beca...,0

In [ ]:
#Merge dataset_2_new & dataset_3_nodate
dataset_2_3 = pd.concat([dataset_2_new, dataset_3_nodate], ignore_index=True, sort=False)
dataset_2_3

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1
...,...,...,...
8426,teens walk free after gangrape conviction,NaN,1
8427,school named for munichmassacre mastermind,NaN,1
8428,russia unveils satan missile,NaN,0
8429,check out hillarythemed haunted house,NaN,0
8430,cannabis aficionados develop thca crystalline ...,NaN,NaN

In [ ]:
#Merge dataset_2_new & dataset_4_new
dataset_2_4 = pd.concat([dataset_2_new, dataset_4_new], ignore_index=True, sort=False)
dataset_2_4

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1
...,...,...,...
10339,Trends to Watch,Trends to Watch\n% of readers think this story...,0
10340,Trump Jr. Is Soon To Give A 30-Minute Speech F...,Trump Jr. Is Soon To Give A 30-Minute Speech F...,0
10341,"Ron Paul on Trump, Anarchism & the AltRight",NaN,0
10342,China to accept overseas trial data in bid to ...,SHANGHAI (Reuters) - China said it plans to ac...,1
10343,Vice President Mike Pence Leaves NFL Game Beca...,Vice President Mike Pence Leaves NFL Game Beca...,0

In [ ]:
#Merge dataset_3_nodate & dataset_4_new
dataset_3_4 = pd.concat([dataset_3_nodate, dataset_4_new], ignore_index=True, sort=False)
dataset_3_4

#Data Cleansing

In [ ]:
#suche nach spalten in denen nur leerzeichen im feld text stehen
all_data['text_isSpace'] = list(map(lambda x: x.isspace(), all_data['text']))
#lösche die zeilen in denen nur leerzeichen im text feld stehen
all_data= all_data[all_data['text_isSpace'] == False]

#spalte text_isSpace wider löschen
all_data = all_data.drop(columns=['text_isSpace'], axis=1)

In [ ]:
#finde werte bei denen title und date gleich sind und lösche sie
all_data = all_data.loc[all_data['title']!= all_data['date']]

In [ ]:
#Ergebnisse finden bei denen der Tittel länger ist als der Text
all_data.loc[all_data['title'].str.len() > all_data['text'].str.len()]

,title,text,subject,date,Echt,text_isSpace
11117,MY FAVORITE EXCUSES…Featuring Hillary Rotten C...,Enjoy:,politics,"Apr 17, 2017",0,False
11251,MELANIA TRUMP GIVES POWERFUL SPEECH to Honor ‘...,https://www.youtube.com/watch?v=cJZFepSvxzM,politics,"Mar 30, 2017",0,False
11286,TERRORISM EXPERT SEBASTIAN GORKA On What Next ...,https://www.youtube.com/watch?v=-7Tn4gi_Os8,politics,"Mar 26, 2017",0,False
11288,TRUMP CABINET MEMBER MICK MULVANEY ON DC: “Thi...,https://www.youtube.com/watch?time_continue=2&...,politics,"Mar 26, 2017",0,False
11315,CRYBABY NANCY PELOSI Taunts Trump On Healthcar...,https://www.youtube.com/watch?v=SH0pRtK9sAE,politics,"Mar 24, 2017",0,False
...,...,...,...,...,...,...
21645,(Video) Obama Supporters Sign Petition to NUKE...,These people will support just about anything ...,left-news,"Jun 15, 2015",0,False
21659,[Video] AWESOME: TEXAS MOM FRUSTRATED BY MCKIN...,Here s a mom who knows how to raise her children,left-news,"Jun 11, 2015",0,False
21789,(VIDEO) ALAN DERSHOWITZ – SAD DAY FOR JUSTICE ...,You re At Forefront Of This Cause And As Youn...,left-news,"May 1, 2015",0,False
21868,THIS IS GREAT! ANTI-HILLARY STREET ART POPS UP...,Hillary Clinton s supporters were calling cert...,left-news,"Apr 12, 2015",0,False
21882,ONLY IN DETROIT: SQUATTING ON THE SQUATTER TAK...,You won t want to miss this,left-news,"Apr 9, 2015",0,False

In [ ]:
#manche Texte enthalten nur ein Link zu z.B einem Youtube video. Manchmal wird aber auch nur auf etwas anderes verlinkt, zusätzlich zum text. Filterd etwas schwieriger
all_data.loc[all_data.text.str.contains('http')]

,title,text,subject,date,Echt
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
16,The Internet Brutally Mocks Disney’s New Trum...,A new animatronic figure in the Hall of Presid...,News,"December 19, 2017",0
19,Republican Senator Gets Dragged For Going Aft...,Senate Majority Whip John Cornyn (R-TX) though...,News,"December 16, 2017",0
27,WATCH: Fox Host Calls For A ‘Cleansing’ Of Th...,Judge Jeanine Pirro has continued her scream...,News,"December 10, 2017",0
...,...,...,...,...,...
23426,BOMBSHELL: Classified NATO Report Praises Russ...,21st Century Wire says This latest bombshell r...,Middle-east,"March 6, 2016",0
23440,Watch as Trump Gatecrashes Glenn Beck’s Cruz C...,21st Century Wire says One TV personality Tru...,Middle-east,"February 24, 2016",0
23463,"Eyewitness Says Feds Ambushed Bundys, 100 Shot...",Patrick Henningsen 21st Century Wire UPDATE: 1...,Middle-east,"January 27, 2016",0
23465,‘There’ll be boots on the ground’: US making n...,21st Century Wire says Various parties in Wash...,Middle-east,"January 23, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0

In [ ]:
#Finde alle Zeilen in denen das Datum NICHT diesen String enthält
all_data.loc[~all_data.date.str.contains(', 20')]
#Lösche alle Zeilen die den String nicht enthalten
all_data = all_data.loc[all_data.date.str.contains(', 20')]

In [ ]:
# finde besonders kurze texte
all_data.loc[all_data['text'].str.len() < 20]

#Löschen?
# all_data = all_data.loc[~all_data['text'].str.len() < 20]

,title,text,subject,date,Echt
11117,MY FAVORITE EXCUSES…Featuring Hillary Rotten C...,Enjoy:,politics,"Apr 17, 2017",0
11324,HYSTERICAL! HERE’S WHY TRUMP SAID TO REPORTER:...,Read more:WT,politics,"Mar 23, 2017",0
11447,HOMELAND SECURITY Catering to Illegals? Three ...,Read more: TMZ,politics,"Mar 10, 2017",0
11517,MULTI-MILLIONAIRE Global-Warming Hypocrites LE...,Enjoy:,politics,"Mar 2, 2017",0
11685,ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 20...,Watch:,politics,"Feb 11, 2017",0
11796,TRUMP’S BRILLIANT Director Of Communications O...,Watch:,politics,"Jan 28, 2017",0
11829,WATCH! Anti-Trump Hag Gets Kicked Off Flight A...,Via: GATEWAY PUNDIT,politics,"Jan 22, 2017",0
11847,BREAKING: PRESIDENT TRUMP Signs Most Important...,Via: NPR,politics,"Jan 20, 2017",0
11978,"DELUSIONAL DEMOCRATS Get A Reality Check: “No,...",Via: MRCTV,politics,"Jan 7, 2017",0
12012,PELOSI Lied About “Affordable” Healthcare And ...,Via: WT,politics,"Jan 2, 2017",0
12063,OUCH! Paul Joseph Watson DESTROYS MTV’s Racist...,Enjoy,politics,"Dec 26, 2016",0
12174,ARMY-NAVY CROWD ERUPTS During Trump Interview…...,Watch:,politics,"Dec 10, 2016",0
12333,DEAR DEMOCRATS AND LIBERALS…Stop Complaining A...,Ouch!,politics,"Nov 21, 2016",0
12570,ANTI-HILLARY HALLOWEEN HOUSE Gets Violent Thre...,Via: TMZ,politics,"Oct 30, 2016",0
12610,BRAINIAC HILLARY SUPPORTER DESTROYS TRUMP’S Ho...,Via: TMZ,politics,"Oct 26, 2016",0
12705,WIKILEAKS: No Stamina? Hillary’s Aide Asked To...,Via: Wikileaks,politics,"Oct 17, 2016",0
12710,BREAKING: UNDERCOVER VIDEO Exposes Hillary’s D...,LANGUAGE WARNING!,politics,"Oct 17, 2016",0
12725,TRUMP HATER MEGYN KELLY Pummeled In Ratings Wh...,Via: GP,politics,"Oct 15, 2016",0
13629,WATCH: BEST DESCRIPTION OF UK BREXIT YET…Conse...,Take note America,politics,"Jun 26, 2016",0
14267,RUSH LIMBAUGH Warns Who The GOP Will Choose If...,Wow! Just wow!,politics,"Mar 17, 2016",0
14322,Anti-Trump Protesters Scream Profanities at FO...,Lefty losers,politics,"Mar 11, 2016",0
14457,REPORTER ASKS: Will Obama Golf Instead of Atte...,BRAVE GUY!,politics,"Feb 18, 2016",0
14633,OOPS! WATCH THE BRILLIANT TV AD Trump Made For...,Brilliant,politics,"Jan 18, 2016",0
15210,TRUMP DOES FALLON’S TONIGHT SHOW: Talks about ...,Great interview!,politics,"Sep 13, 2015",0
15251,HAMMER TIME: TRUMP POINTS OUT THE LIES BEHIND ...,This ad is spot on,politics,"Aug 31, 2015",0
15304,(Video) Bill O’Reilly Donald Trump Battle Over...,Spirited debate:,politics,"Aug 18, 2015",0
15449,(VIDEO) BRAVO! TV HOST SCORCHES OBAMA FOR HIS ...,I VE HAD IT!,politics,"Jul 20, 2015",0
16261,BREAKING: PRESIDENT TRUMP Signs Most Important...,Via: NPR,Government News,"Jan 20, 2017",0
16278,PELOSI Lied About “Affordable” Healthcare And ...,Via: WT,Government News,"Jan 2, 2017",0
18805,MY FAVORITE EXCUSES…Featuring Hillary Rotten C...,Enjoy:,left-news,"Apr 17, 2017",0
19050,MULTI-MILLIONAIRE Global-Warming Hypocrites LE...,Enjoy:,left-news,"Mar 2, 2017",0
19156,ARROGANT ILLEGAL ALIEN Who Voted 5 Times In 20...,Watch:,left-news,"Feb 11, 2017",0
19235,TRUMP’S BRILLIANT Director Of Communications O...,Watch:,left-news,"Jan 28, 2017",0
19263,WATCH! Anti-Trump Hag Gets Kicked Off Flight A...,Via: GATEWAY PUNDIT,left-news,"Jan 22, 2017",0
19400,OUCH! Paul Joseph Watson DESTROYS MTV’s Racist...,Enjoy,left-news,"Dec 26, 2016",0
19572,DEAR DEMOCRATS AND LIBERALS…Stop Complaining A...,Ouch!,left-news,"Nov 21, 2016",0
19717,ANTI-HILLARY HALLOWEEN HOUSE Gets Violent Thre...,Via: TMZ,left-news,"Oct 30, 2016",0
20370,WATCH: BEST DESCRIPTION OF UK BREXIT YET…Conse...,Take note America,left-news,"Jun 26, 2016",0
20891,Anti-Trump Protesters Scream Profanities at FO...,Lefty losers,left-news,"Mar 11, 2016",0

In [ ]:
#Kurze Titel finden, Wahrscheinlich nicht löschen?
all_data.loc[all_data['title'].str.len() < 20]

,title,text,subject,date,Echt
14960,JOKE OF THE DAY,My wife and I went into town and visited a sho...,politics,"Nov 7, 2015",0
21228,No Words… [VIDEO],For the first time in the history of 100% FED ...,left-news,"Dec 12, 2015",0
22064,Boiler Room EP #118,Tune in to the Alternate Current Radio Network...,US_News,"July 20, 2017",0
22330,Boiler Room EP #87,Tune in to the Alternate Current Radio Network...,US_News,"December 8, 2016",0
22448,Boiler Room EP #78,Tune in to the Alternate Current Radio Network...,US_News,"October 12, 2016",0
22847,Boiler Room EP #118,Tune in to the Alternate Current Radio Network...,Middle-east,"July 20, 2017",0
23113,Boiler Room EP #87,Tune in to the Alternate Current Radio Network...,Middle-east,"December 8, 2016",0
23231,Boiler Room EP #78,Tune in to the Alternate Current Radio Network...,Middle-east,"October 12, 2016",0

#Training

In [ ]:
fake =  pd.read_csv('data\Fake.csv')
true = pd.read_csv('data\True.csv')

In [ ]:
#wie viele Datensätze haben ein Leerzeichen im text (oder zwei)
fake.loc[fake['text'] ==' '].count() + fake.loc[fake['text'] =='  '].count()

In [ ]:
#suche Nach datensatz mit disem Titel
fake.loc[fake['title'] == 'https://100percentfedup.com/served-roy-moore-vietnamletter-veteran-sets-record-straight-honorable-decent-respectable-patriotic-commander-soldier/']

In [ ]:
#Nur das Datum ausgeben lassen
fake.date[9358]

In [ ]:
#test